dist: trusty
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - 'pypy'
install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - pip install -U setuptools
  - pip install pytest --upgrade
script:
  - python setup.py install
  - coverage run --source flask_rest_jsonapi -m pytest -v
after_success:
  - coveralls
before_deploy: "python setup.py sdist"
deploy:
  - provider: releases
    api_key:
      secure: your_github_password_encrypted_using_your_travis_project_private_key
    file_glob: true
    file: dist/Flask-REST-JSONAPI-*.tar.gz
    skip_cleanup: true
    on:
      tags: true
      repo: miLibris/flask-rest-jsonapi
  - provider: pypi
    user: akira-dev
    password:
      secure: your_pypi_password_encrypted_using_your_travis_project_private_key
    on:
      tags: true
      repo: miLibris/flask-rest-jsonapi
